# Limpieza de datos

La mayoría de la gente piensa que ser científico de datos significa estar corriendo modelos avanzados de Machine Learning todo el tiempo. La realidad es muy distinta:

![Tiempo de un científico de datos](./img/datascientist_time.jpeg)

La gran mayoría del tiempo se va **limpiando y organizando** los datos con los que queremos trabajar.

Los científicos de datos utilizamos herramientas como Pandas, Numpy, Matplotlib y Seaborn para limpiar los datos con los que queremos hacer algo.

## ETL

Un tipo de tarea que realizamos con gran frecuencia los científicos de datos son los **ETL**.

![Proceso de ETL](./img/etl.png)

ETL es un acrónimo que significa Extract, Transform, Load. Es un proceso que se utiliza para extraer datos de una fuente, transformarlos en un formato que sea adecuado para el análisis y cargarlos en una base de datos o algún otro sistema de almacenamiento.

## Ejemplo práctico

Los datos que usaremos para esta limpieza y nuestro siguiente análisis son datos de incidencia delictiva en nuestro país.

La iniciativa de datos abiertos del gobierno de México nos proporciona datos de incidencia delictiva desde 2015 hasta la fecha. Los datos se actualizan todos los meses y se pueden descargar desde el siguiente enlace: https://www.gob.mx/sesnsp/acciones-y-programas/datos-abiertos-de-incidencia-delictiva

---

Como podemos ver en el portal, se proporcionan los datos tanto a nivel estatal como a nivel municipal. En este caso, utilizaremos los datos a nivel estatal.

Descarguemos los datos y guardemos el archivo CSV en la carpeta data con el nombre `datos_delitos.csv`.

---

Ahora leamos el archivo CSV y veamos cómo se ven los datos.

Primero que nada, importemos pandas

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('data/datos_delitos.csv', encoding='latin1')

Aquí tenemos un error muy común que suele ocurrir cuando un archivo se guarda en una computadora con cierto "encoding". 

Un encoding es una tabla que relaciona un número con un carácter. Por ejemplo, en la tabla ASCII, el número 65 corresponde a la letra "A".

Si el archivo que estamos leyendo fue guardado con un encoding distinto al que pandas espera, nos arrojará un error. 

Para solucionar esto, podemos utilizar el parámetro `encoding` de la función `pd.read_csv()` y especificar el encoding correcto.

¿Pero cómo sabemos con qué encoding cuenta el archivo?

La realidad es que la gran mayoría de los archivos los encontrarán en encoding utf-8 y Pandas no va a dar ningún error. Aquí estamos teniendo este problema porque la computadora que utilizan para generar este archivo uso un encoding diferente a utf-8.

En México, por lo general, si un archivo no está en utf-8, lo más seguro es que esté en `ISO-8859-1` o `latin1`.

Intentemos cargar el archivo especificando el encoding `ISO-8859-1`.

In [11]:
df = pd.read_csv('data/datos_delitos.csv', encoding='ISO-8859-1')
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0

Y vemos que ya podemos leer correctamente el archivo.


¿Existe alguna forma de verificar el encoding de un archivo sin tener que estar adivinando?

ChatGTP generó el siguiente código:

In [12]:
import chardet

def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        rawdata = f.read()
    result = chardet.detect(rawdata)
    return result

file_path = './data/datos_delitos.csv'
encoding_info = detect_encoding(file_path)
print(f"Detected encoding: {encoding_info['encoding']}")

Detected encoding: Windows-1252

Sigamos...

In [13]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,20,22,34,35,34,37,NaN,NaN,NaN,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,NaN,NaN,NaN,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,183,174,199,208,177,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31360 entries, 0 to 31359
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     31360 non-null  int64
 1   Clave_Ent               31360 non-null  int64
 2   Entidad                 31360 non-null  str
 3   Bien jurídico afectado  31360 non-null  str
 4   Tipo de delito          31360 non-null  str
 5   Subtipo de delito       31360 non-null  str
 6   Modalidad               31360 non-null  str
 7   Enero                   31360 non-null  int64
 8   Febrero                 31360 non-null  int64
 9   Marzo                   31360 non-null  int64
 10  Abril                   31360 non-null  int64
 11  Mayo                    31360 non-null  int64
 12  Junio                   31360 non-null  int64
 13  Julio                   28224 non-null  float64
 14  Agosto                  28224 non-null  float64
 15  Septiembre              28224 non-null  float64
 16  Octubre                 28224 non-null  float64
 17  Noviembre               28224 non-null  float64
 18  Diciembre               28224 non-null  float64
dtypes: float64(6), int64(8), str(5)
memory usage: 4.5 MB

Bien. Están muy bien los datos. Sin embargo, tenemos un problema con el que es muy común encontrarnos. 

Resulta que el formato en el que está el archivo es fácil entender por seres humanos:


```markdown
| Año      | Entidad  | Enero    | Febrero  | Mes X    |
|----------|----------|----------|----------|----------|
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
```

Vemos que tenemos los meses como encabezados. Es decir, el archivo está tratando cada mes como si fuera una variable. 

Nosotros como científicos de datos estamos más interesados en conjuntos de datos que no estén en este formato de "resumen" o "tabla dinámica". Para nosotros, lo ideal sería que cada mes fuera simplemente una observación más en nuestro conjunto de datos. Es decir, queremos transformar la tabla de arriba en:

```markdown
| Año      | Entidad  | Mes        |
|----------|----------|------------|
|   ...    |   ...    |   Enero    |
|   ...    |   ...    |   Febrero  |
|   ...    |   ...    |   Marzo    |
|   ...    |   ...    |   Abril    |
|   ...    |   ...    |   Mes X    |
```

A este tipo de formato le llamos "formato largo de datos".

Haremos las siguientes limpiezas:
* Transformar los nombres de las columnas para que no tengan caracteres especiales y estén siempre en minúsculas
* Convertir el dataset a un formato de datos "largo"

In [15]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [16]:
len(df.columns)

19

### Limpiar nombres de columnas

In [17]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)
    
    df.columns = columnas_limpias
    
    return df

In [18]:
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [19]:
df = limpiar_columnas(df)

In [20]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0

Muy bien. Ahora lo que queremos hacer es quitar algunas columnas. Nos interesan nada más las siguientes:

In [21]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
31355  2024       Zacatecas
31356  2024       Zacatecas
31357  2024       Zacatecas
31358  2024       Zacatecas
31359  2024       Zacatecas

[31360 rows x 2 columns]

In [22]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

### Formato largo de datos

Ahora, usaremos el método `melt` para convertir las columnas a observaciones.

Queremos convervar las coumnas:
* anio
* clave_ent
* entidad
* tipo_de_delito
* subtipo_de_delito
* modalidad

El resto de las columnas las vamos a juntar en una nueva columna llamada "nombre_mes" y sus valores los vamos a sumar en otra llamada "frecuencia"

In [23]:
print("Shape ", df.shape)

Shape  (31360, 18)

In [24]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [25]:
print("Shape: ", datos_long.shape)

Shape:  (376320, 8)

In [26]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1.0
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0.0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2.0
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0.0

In [27]:
datos_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 376320 entries, 0 to 376319
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               376320 non-null  int64
 1   clave_ent          376320 non-null  int64
 2   entidad            376320 non-null  str
 3   tipo_de_delito     376320 non-null  str
 4   subtipo_de_delito  376320 non-null  str
 5   modalidad          376320 non-null  str
 6   nombre_mes         376320 non-null  str
 7   frecuencia         357504 non-null  float64
dtypes: float64(1), int64(2), str(5)
memory usage: 23.0 MB

Supongamos que para este análisis, no nos importan los niveles subtipo de delito y modalidad. O sea, no queremos tener la distinción entre homicidios dolosos y culposos (sé que son bastante diferentes, pero simplifiquemos nuestro ejemplo).

Vamos a agrupar nuestro dataframe por anio, clave_ent, entidad, tipo_de_delito y nombre_mes. Esto hará que todos los tipos de homicidios se sumen al tipo "homicidio" o todos los tipos de robo de vehículo (con o sin violencia) se sumen a "robo de vehículo".

In [28]:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [29]:
datos_long[datos_long.tipo_de_delito == 'Robo'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
117513,2022,21,Puebla,Robo,noviembre,2453.0
391,2015,1,Aguascalientes,Robo,marzo,1001.0
101186,2021,19,Nuevo León,Robo,diciembre,1331.0
11904,2015,25,Sinaloa,Robo,abril,951.0
141989,2024,8,Chihuahua,Robo,julio,0.0
110314,2022,6,Colima,Robo,octubre,541.0
151108,2024,27,Tabasco,Robo,febrero,768.0
134786,2023,25,Sinaloa,Robo,diciembre,542.0
55111,2018,19,Nuevo León,Robo,marzo,1332.0
125670,2023,6,Colima,Robo,junio,465.0
129027,2023,13,Hidalgo,Robo,enero,1163.0
60866,2018,31,Yucatán,Robo,diciembre,235.0
7594,2015,16,Michoacán de Ocampo,Robo,octubre,1237.0
23424,2016,17,Morelos,Robo,abril,1642.0
73829,2019,26,Sonora,Robo,julio,519.0

Mostremos todos los estados y su respectiva clave

In [30]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
480            2                  Baja California
960            3              Baja California Sur
1440           4                         Campeche
2880           7                          Chiapas
3360           8                        Chihuahua
3840           9                 Ciudad de México
1920           5             Coahuila de Zaragoza
2400           6                           Colima
4320          10                          Durango
4800          11                       Guanajuato
5280          12                         Guerrero
5760          13                          Hidalgo
6240          14                          Jalisco
7200          16              Michoacán de Ocampo
7680          17                          Morelos
6720          15                           México
8160          18                          Nayarit
8640          19                       Nuevo León
9120          20                           Oaxaca
9600          21                           Puebla
10080         22                        Querétaro
10560         23                     Quintana Roo
11040         24                  San Luis Potosí
11520         25                          Sinaloa
12000         26                           Sonora
12480         27                          Tabasco
12960         28                       Tamaulipas
13440         29                         Tlaxcala
13920         30  Veracruz de Ignacio de la Llave
14400         31                          Yucatán
14880         32                        Zacatecas

Ahora Veamos todos los datos de delitos de una entidad en específico. Por ejemplo, Nuevo león

In [31]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
85706,2020,19,Nuevo León,Lesiones,diciembre,584.0
24254,2016,19,Nuevo León,Incumplimiento de obligaciones de asistencia f...,diciembre,51.0
101063,2021,19,Nuevo León,Incumplimiento de obligaciones de asistencia f...,septiembre,51.0
101239,2021,19,Nuevo León,Violación equiparada,marzo,47.0
146941,2024,19,Nuevo León,Amenazas,agosto,0.0
70271,2019,19,Nuevo León,Falsificación,septiembre,71.0
147082,2024,19,Nuevo León,Feminicidio,octubre,0.0
70118,2019,19,Nuevo León,Acoso sexual,diciembre,29.0
8846,2015,19,Nuevo León,Fraude,diciembre,191.0
116310,2022,19,Nuevo León,Evasión de presos,junio,1.0
24115,2016,19,Nuevo León,Delitos cometidos por servidores públicos,marzo,36.0
70471,2019,19,Nuevo León,Robo,marzo,1198.0
8809,2015,19,Nuevo León,Falsedad,agosto,1.0
54791,2018,19,Nuevo León,Amenazas,septiembre,508.0
70436,2019,19,Nuevo León,Otros delitos que atentan contra la libertad y...,mayo,38.0

In [32]:
datos_long[(datos_long['clave_ent'] > 19) &  (datos_long['clave_ent'] < 24) & (datos_long['tipo_de_delito'] == 'Homicidio')].sample(15)

        anio  clave_ent       entidad tipo_de_delito  nombre_mes  frecuencia
132706  2023         21        Puebla      Homicidio     octubre        82.0
9344    2015         20        Oaxaca      Homicidio        mayo       129.0
133176  2023         22     Querétaro      Homicidio       abril        54.0
41017   2017         22     Querétaro      Homicidio      agosto        47.0
132707  2023         21        Puebla      Homicidio  septiembre       111.0
9340    2015         20        Oaxaca      Homicidio     febrero       105.0
71258   2019         21        Puebla      Homicidio   diciembre       131.0
9827    2015         21        Puebla      Homicidio  septiembre        99.0
24702   2016         20        Oaxaca      Homicidio       junio       132.0
26138   2016         23  Quintana Roo      Homicidio   diciembre        16.0
148537  2024         22     Querétaro      Homicidio      agosto         0.0
10307   2015         22     Querétaro      Homicidio  septiembre        40.0
148066  2024         21        Puebla      Homicidio     octubre         0.0
41497   2017         23  Quintana Roo      Homicidio      agosto        44.0
41023   2017         22     Querétaro      Homicidio       marzo        32.0

### Valores de fechas

Finalmente, queremos tener una columna "fecha". Actualmente tenemos el año y el nombre del mes, pero no tenemos como tal una columna que tenga un tipo de dato fecha. Eso hace que filtrar por fecha sea complicado.

Por ejemplo, si queremos conocer todos los homicidios de Oaxaca en enero 2024, haríamos lo siguiente:

In [33]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero') 
]

        anio  clave_ent entidad tipo_de_delito nombre_mes  frecuencia
147579  2024         20  Oaxaca      Homicidio      enero       157.0

Creemos una columna de fecha. 

Primero tenemos que convertir el nombre de mes a un número, en donde 1 es enero, 2 febrero, etc.

In [34]:
datos_long.sample(2)

        anio  clave_ent    entidad      tipo_de_delito nombre_mes  frecuencia
153541  2024         32  Zacatecas  Tráfico de menores     agosto         0.0
21869   2016         14    Jalisco            Lesiones      julio      1142.0

In [35]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna
104374,2021,26,Sonora,Fraude,octubre,52.0,dato vacío
24862,2016,20,Oaxaca,Rapto,octubre,0.0,dato vacío
93880,2021,4,Campeche,Narcomenudeo,febrero,12.0,dato vacío
58748,2018,27,Tabasco,Falsificación,mayo,17.0,dato vacío
32781,2017,5,Coahuila de Zaragoza,Electorales,noviembre,0.0,dato vacío
150293,2024,26,Sonora,Allanamiento de morada,julio,0.0,dato vacío

In [36]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
40553,2017,21,Puebla,Hostigamiento sexual,julio,1.0,dato vacío,7
20304,2016,11,Guanajuato,Evasión de presos,abril,0.0,dato vacío,4
146537,2024,18,Nayarit,Electorales,julio,0.0,dato vacío,7
142584,2024,10,Durango,Abuso sexual,abril,44.0,dato vacío,4
100765,2021,18,Nayarit,Violación simple,agosto,13.0,dato vacío,8

In [37]:
datos_long["frecuencia_mas_10"] = datos_long["frecuencia"] + 10
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10
95975,2021,8,Chihuahua,Violación simple,septiembre,88.0,dato vacío,9,98.0
30657,2016,32,Zacatecas,Trata de personas,noviembre,0.0,dato vacío,11,10.0
102695,2021,22,Querétaro,Violación simple,septiembre,33.0,dato vacío,9,43.0
128564,2023,12,Guerrero,Secuestro,mayo,2.0,dato vacío,5,12.0
10777,2015,23,Quintana Roo,Homicidio,agosto,51.0,dato vacío,8,61.0

In [38]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes
74353,2019,27,Tabasco,Violación equiparada,agosto,0.0,dato vacío,8,10.0,20198
43689,2017,28,Tamaulipas,Aborto,noviembre,1.0,dato vacío,11,11.0,201711
2973,2015,7,Chiapas,Corrupción de menores,noviembre,7.0,dato vacío,11,17.0,201511
52883,2018,15,México,Contra el medio ambiente,septiembre,50.0,dato vacío,9,60.0,20189
93494,2021,3,Baja California Sur,Rapto,diciembre,0.0,dato vacío,12,10.0,202112
55849,2018,21,Puebla,Falsedad,agosto,10.0,dato vacío,8,20.0,20188

In [39]:
# yyyy-mm-dd, yy-mm-dd, yymmdd, yyyy/dd/mm

In [40]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes,fecha
27205,2016,25,Sinaloa,Otros delitos del Fuero Común,agosto,13.0,dato vacío,8,23.0,20168,2016-08-01
141539,2024,7,Chiapas,Trata de personas,septiembre,0.0,dato vacío,9,10.0,20249,2024-09-01
35191,2017,10,Durango,Evasión de presos,marzo,0.0,dato vacío,3,10.0,20173,2017-03-01
68814,2019,16,Michoacán de Ocampo,Falsedad,junio,3.0,dato vacío,6,13.0,20196,2019-06-01
3706,2015,8,Chihuahua,Otros delitos que atentan contra la libertad p...,octubre,53.0,dato vacío,10,63.0,201510,2015-10-01

In [41]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
119297,2022,25,Sinaloa,Incumplimiento de obligaciones de asistencia f...,julio,11.0,7,21.0,20227,2022-07-01
130653,2023,17,Morelos,Corrupción de menores,noviembre,3.0,11,13.0,202311,2023-11-01
64210,2019,6,Colima,Otros delitos que atentan contra la vida y la ...,octubre,0.0,10,10.0,201910,2019-10-01
57767,2018,25,Sinaloa,Extorsión,septiembre,6.0,9,16.0,20189,2018-09-01
89506,2020,27,Tabasco,Homicidio,octubre,69.0,10,79.0,202010,2020-10-01

Veamos los homicidios en oaxaca de enero 2024 a la fecha

In [42]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
147579,2024,20,Oaxaca,Homicidio,enero,157.0,1,167.0,20241,2024-01-01
147580,2024,20,Oaxaca,Homicidio,febrero,170.0,2,180.0,20242,2024-02-01
147583,2024,20,Oaxaca,Homicidio,marzo,190.0,3,200.0,20243,2024-03-01
147576,2024,20,Oaxaca,Homicidio,abril,208.0,4,218.0,20244,2024-04-01
147584,2024,20,Oaxaca,Homicidio,mayo,236.0,5,246.0,20245,2024-05-01
147582,2024,20,Oaxaca,Homicidio,junio,202.0,6,212.0,20246,2024-06-01
147581,2024,20,Oaxaca,Homicidio,julio,0.0,7,10.0,20247,2024-07-01
147577,2024,20,Oaxaca,Homicidio,agosto,0.0,8,10.0,20248,2024-08-01
147587,2024,20,Oaxaca,Homicidio,septiembre,0.0,9,10.0,20249,2024-09-01
147586,2024,20,Oaxaca,Homicidio,octubre,0.0,10,10.0,202410,2024-10-01
147585,2024,20,Oaxaca,Homicidio,noviembre,0.0,11,10.0,202411,2024-11-01
147578,2024,20,Oaxaca,Homicidio,diciembre,0.0,12,10.0,202412,2024-12-01

In [43]:
datos_finales = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales.head(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,abril,2015-04-01,0.0
1,2015,1,Aguascalientes,Aborto,agosto,2015-08-01,0.0

Ya que tenemos muestros datos bien estructurados, los podemos guardar en nuestra computadora. Los guardaremos con el nombre "delitos.csv"

In [44]:
datos_finales.to_csv('data/delitos.csv', index=False)